

INSERT INTO `articulos` (`id`, `nombre`, `categoria`, `descripcion`, `imagen_url`, `enlace_externo`, `precio`) VALUES
( 'Aro de Baloncesto en Acero', 'Equipamiento', 'Tipo de Aro: Estándar\r\nDimensiones internas: 46 cm\r\nMaterial: Acero Sólido\r\nEspesor del aro: 60 mm\r\nSistema de sujeción: Atornillable\r\nGanchos para malla: 12', 'https://www.ventosport.com/wp-content/uploads/2025/05/aro-de-baloncesto-en-acero-1.png', 'https://www.ventosport.com/producto/aro-de-baloncesto-en-acero/', 120000.00),
('Balón de Fútbol Semiprofesional Vento Pro Híbrido', 'Balones', 'Material: PU de alta calidad, garantizando suavidad al tacto y durabilidad.\r\n\r\nConstrucción: Híbrida, combinando paneles termosellados y cosidos para mayor resistencia.\r\n\r\nPaneles: 24 paneles, optimizando la aerodinámica y el control del balón.\r\n\r\nTamaños disponibles:\r\n\r\nTamaño 5: Circunferencia de 67-70 cm, peso ajustado y rebote entre 135-155 cm.\r\n\r\nTamaño 4: Circunferencia de 63-66 cm, adaptado para jugadores jóvenes o entrenamientos específicos.\r\n\r\nTerreno recomendado: Césped natural o sintético, ofreciendo versatilidad en diferentes superficies.\r\n\r\nCertificaciones: Cumple con estándares internacionales de calidad, asegurando un rendimiento óptimo en competencias.', 'https://www.ventosport.com/wp-content/uploads/2025/01/balon-de-futbol-semiprofesional-vento-pro-hibrido-t4-1.webp', 'https://www.ventosport.com/producto/balon-de-futbol-semiprofesional-vento-pro-hibrido/', 100000.00),
( 'Balón de Voleibol Semiprofesional Vento V5 Pro', 'Balones', 'Desempeño semiprofesional con construcción laminada y diseño de 8 paneles. Ideal para competencias y entrenamientos en canchas interiores. Cumple con estándares de la FIVB.', 'https://www.ventosport.com/wp-content/uploads/2025/01/balon-de-voleibol-semiprofesional-vento-v5-pro-1.webp', 'https://www.ventosport.com/producto/balon-de-voleibol-semiprofesional-vento-v5-pro/', 85000.00),
( 'Raqueta Ping Pong Profesional 5 Estrellas', 'Equipamiento', 'Número de Capas: 4 capas\r\nGrosor de la Madera: 6.5 mm\r\nTipo de goma: Lisa (Invertida)\r\nGrosor de la goma: 3 mm\r\nMaterial del mango: Madera\r\nPeso: 176 gr', 'https://www.ventosport.com/wp-content/uploads/2025/05/raqueta-de-ping-pong-profesional-2.png', 'https://www.ventosport.com/producto/raqueta-ping-pong-profesional-5-estrellas/', 55000.00),
('Malla Balonera x12 Unds', 'Accesorio', 'Capacidad: 12 - 10 Balones Aprox\r\nMaterial: Poliéster\r\nSistema de cierre: Cordón de ajuste\r\nTipo de tirante: Cordón', 'https://www.ventosport.com/wp-content/uploads/2025/05/Malla-Balonera-x12-Unds-3.png', 'https://www.ventosport.com/producto/malla-balonera-x12-unds/', 80000.00),
( 'Balón de Baloncesto Profesional Vento Indoor-Outdoor', 'Balones', 'Diseñado para competiciones profesionales, el Vento Indoor-Outdoor combina material PU premium, construcción laminada-corrugada y diseño de 8 paneles para un rendimiento superior en canchas interiores y exteriores lisas. Disponible en tamaños 7 y 6', 'https://www.ventosport.com/wp-content/uploads/2025/01/balon-de-baloncesto-profesional-vento-indoor-outdoor-1.webp', 'https://www.ventosport.com/producto/balon-de-baloncesto-profesional-vento-indoor-outdoor/', 150000.00),
( 'Cuerda de Salto', 'Accesorio', 'Tipo de cuerda: Fija\r\nMaterial cuerda: Silicona\r\nDimensión: 214 cm Largo\r\nMaterial mangos: Plástico\r\nLargo del mango: 11 cm', 'https://www.ventosport.com/wp-content/uploads/2025/05/cuerda-de-salto-1.png', 'https://www.ventosport.com/producto/cuerda-de-salto/', 20000.00),
( 'Tula Balonera x 12 Unds', 'Accesorio', 'Capacidad: 12 Balones Aprox\r\nDimensiones: 85 cm Alto x 70 cm Ancho x 46 cm Largo Profundidad\r\nMaterial: Poliéster\r\nSistema de cierre: Cordón de ajuste con cierre de seguridad\r\nTipo de tirante: Correa ajustable', 'https://www.ventosport.com/wp-content/uploads/2025/05/Tula-Balonera-x-12-Und-1.png', 'https://www.ventosport.com/producto/tula-balonera-x-12-und/', 90000.00),
( 'Malla para Aro de Baloncesto', 'Accesorio', 'Material: Nylon, Fibra de Poliéster\r\nLazos/Ganchos: 10\r\nCalibre del hilo: 3mm - 5mm\r\nUso: Interiores - Exteriores', 'https://www.ventosport.com/wp-content/uploads/2025/05/DSC0238.png', 'https://www.ventosport.com/wp-content/uploads/2025/05/DSC0238.png', 30000.00),
( 'Pelotas de Ping Pong X60 Unidades', 'Equipamiento', 'Material: Plástico de alta resistencia\r\nDiámetro: 40 mm\r\nPeso: 2,5 gr', 'https://www.ventosport.com/wp-content/uploads/2025/05/pelotas-de-ping-pong-x60-unidades-1.png', 'https://www.ventosport.com/producto/pelotas-de-ping-pong-x60-unidades/', 70000.00);

